# Generated by Django 4.2.7 on 2023-11-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
